# Generated by Django 6.0.5 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_boat_type', models.CharField(blank=True, max_length=5)),
                ('preferred_seat', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type', models.CharField(blank=True, max_length=5)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
