# Generated by Django 6.0.5 on 2026-05-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachpreference',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachpreference',
            name='rower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferredpairing',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_pairings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferredpairing',
            name='rowers',
            field=models.ManyToManyField(related_name='in_pairings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coachpreference',
            unique_together={('coach', 'rower')},
        ),
    ]
