# Generated by Django 6.0.5 on 2026-05-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('training_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewseat',
            name='rower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teams.team'),
        ),
        migrations.AddField(
            model_name='crewassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crews', to='training_sessions.session'),
        ),
        migrations.AlterUniqueTogether(
            name='crewseat',
            unique_together={('crew', 'seat_number')},
        ),
    ]
