# Generated by Django 6.0.5 on 2026-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
